openapi: 3.0.3
info:
  title: Delivery
  description: |
    Ensures that all ordered items are delivered to the guest and that they are registered for billing.
  version: 1.0.0
paths:
  /orderInformation:
    post:
      summary: Forward information about the order
      description: |
        The order information received from the guest is forwarded to the 
        assistance manager. 
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/orderInformation" 
            examples:
                DeliveryAndDrinksInformationForThreePeople:
                  summary: Information about food & drinks for three persons
                  value:
                    {
                      "guest": 2,
                      "order": 1,
                      "food" : [
                            1,
                            2,
                            1
                      ],
                       "drink": [
                            1,
                            2,
                            2
                      ] 
                    }  
      responses:
        "200":
          description: Delivery and drinks information has been forwarded successfully
          content:
            application/json: 
              schema:
                $ref: "#/components/schemas/forwardingOrderInformationConfirmation"   
  /preparedNotification:
    post:
      summary: Send notification to assistant manager
      description: |
        When a food is prepared the assistant manager can be informed
        via this endpoint.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/preparedNotification"
            examples:
              MealPreparedNotifcation:
                summary: Notification about a specific meal for a specific guest which is prepared
                value:
                  {
                    "guest": 2,
                    "food" : 1
                  }  
      responses:
        "200":
          description: Notification has been successfull
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/preparedNotificationConfirmation"
components:
  schemas:
    identifier:
      type: integer
      minimum: 0
    identifiers:
      type: array
      items: 
        $ref: "#/components/schemas/identifier" 
    orderInformation:
      type: object
      properties:
        guest:
          $ref: "#/components/schemas/identifier"
        order:
          $ref: "#/components/schemas/identifier"
        food:
          $ref: "#/components/schemas/identifiers"
        drinks:
          $ref: "#/components/schemas/identifiers"
    forwardingOrderInformationConfirmation:
      type: object
      properties:
        orderInformation:
          description: Delivery Information for Guest 
          $ref: "#/components/schemas/identifier" 
    preparedNotification:
      type: object
      properties:
        guest: 
          $ref: "#/components/schemas/identifier" 
        meal:
          $ref: "#/components/schemas/identifier" 
    preparedNotificationConfirmation:
      type: object
      properties:
        preparedNotification: 
          description: Notification success
          $ref: "#/components/schemas/identifier" 