openapi: 3.0.3
info:
    title: Guest experience
    description: |
        Provides a menu with daily offers tailored to customers, which is compliant to the legal rules of the country.
    version: 1.0.0
paths:
    /menu:
        get:
            summary: Registers as guest and request the daily menu
            description: |
                Returns a guest identifier together with a menu structure containing the menu items together with nutrition and price information.
            operationId: get-menu
            responses:
                "200":
                    description: "OK"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/menu"
                            examples:
                                SmallMenu:
                                    summary: A small menu with two meals and two drinks
                                    value:
                                        {
                                            "guest": 2,
                                            "food":
                                                [
                                                    {
                                                        "id": 1,
                                                        "name": "Burger",
                                                        "nutrition": ["A", "B", "C"],
                                                        "price": 20.2,
                                                    },
                                                    {
                                                        "id": 2,
                                                        "name": "Wiener Schnitzel",
                                                        "nutrition": ["D", "E"],
                                                        "price": 10.2,
                                                    },
                                                ],
                                            "drinks":
                                                [
                                                    {
                                                        "id": 1,
                                                        "name": "Soda",
                                                        "nutrition": ["H"],
                                                        "price": 4.4,
                                                    },
                                                    {
                                                        "id": 2,
                                                        "name": "Beer",
                                                        "nutrition": [],
                                                        "price": 5.4,
                                                    },
                                                ],
                                        }
    /prices:
        get:
            summary: gets menu item prices
            description: |
                Returns a menu structure containing the menu items together with the price information.
            operationId: get-prices
            responses:
                "200":
                    description: "OK"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/prices"
                            examples:
                                SmallMenu:
                                    summary: A small menu with two meals and two drinks
                                    value:
                                        {
                                            "food":
                                                [
                                                    {"id": 1, "name": "Burger", "price": 20.2},
                                                    {
                                                        "id": 2,
                                                        "name": "Wiener Schnitzel",
                                                        "price": 10.2,
                                                    },
                                                ],
                                            "drinks":
                                                [
                                                    {"id": 1, "name": "Soda", "price": 4.4},
                                                    {"id": 2, "name": "Beer", "price": 5.4},
                                                ],
                                        }

components:
    parameters:
        guestParam:
            description: Identifier of a guest in the restaurant
            name: guest
            in: path
            required: true
            schema:
                $ref: "#/components/schemas/identifier"
        orderParam:
            description: Identifier of an order in the restaurant
            name: order
            in: path
            required: true
            schema:
                $ref: "#/components/schemas/identifier"
    schemas:
        errorMessage:
            type: string
            maxLength: 256
            description: A text message describing an error
        money:
            type: number
            description: Euros
            minimum: 0
            example: 10.0
        nutrition:
            type: string
            enum: ["A", "B", "C", "D", "E", "F", "G", "H", "L", "M", "N", "O", "P", "R"]
            description: |
                Contains the nutrition information according to Austrian law, see <https://www.wko.at/branchen/tourismus-freizeitwirtschaft/gastronomie/weiterfuehrende_infos_allergene.html>
            example: "A"
        identifier:
            type: integer
            minimum: 0
            example: 1
        menuItem:
            type: object
            properties:
                id:
                    $ref: "#/components/schemas/identifier"
                name:
                    type: string
                    maxLength: 50
                    description: A name describing the menu item
                    example: Wiener Schnitzel
                nutrition:
                    type: array
                    minimum: 0
                    items:
                        $ref: "#/components/schemas/nutrition"
                price:
                    $ref: "#/components/schemas/money"
        menu:
            type: object
            properties:
                guest:
                    $ref: "#/components/schemas/identifier"
                food:
                    type: array
                    minimum: 1
                    items:
                        $ref: "#/components/schemas/menuItem"
                drinks:
                    type: array
                    minimum: 1
                    items:
                        $ref: "#/components/schemas/menuItem"
        itemPrice:
            type: object
            properties:
                id:
                    $ref: "#/components/schemas/identifier"
                name:
                    type: string
                    maxLength: 50
                    description: A name describing the menu item
                    example: Wiener Schnitzel
                price:
                    $ref: "#/components/schemas/money"
        prices:
            type: object
            properties:
                food:
                    type: array
                    minimum: 1
                    items:
                        $ref: "#/components/schemas/itemPrice"
                drinks:
                    type: array
                    minimum: 1
                    items:
                        $ref: "#/components/schemas/itemPrice"
